---
abstract: 'Perl interface to libgpgme'
author:
  - 'Florian Ragwitz, C<< <rafl at debian.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-GpgME
no_index:
  directory:
    - examples
    - ext
    - inc
    - t
requires:
  IO::Scalar: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
