---
abstract: 'Perl interface to libgpgme'
author:
  - 'Florian Ragwitz, C<< <rafl at debian.org> >>'
build_requires:
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-GpgME
no_index:
  directory:
    - ext
    - inc
    - t
    - examples
requires:
  IO::Scalar: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
